<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KhsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $khs = [
            [   'mahasiswa_id' => 4,
                'matakuliah_id'=> 1,
                'nilai_angka' => 95,
                'nilai_huruf'=>'A',
            ],
            [   'mahasiswa_id' => 4,
                'matakuliah_id'=> 2,
                'nilai_angka' => 90,
                'nilai_huruf'=>'A',
            ],
            [   'mahasiswa_id' => 4,
                'matakuliah_id'=> 3,
                'nilai_angka' => 79,
                'nilai_huruf'=>'B+',
            ],
            [   'mahasiswa_id' => 4,
                'matakuliah_id'=> 4,
                'nilai_angka' => 85,
                'nilai_huruf'=>'A',
            ],
            [   'mahasiswa_id' => 5,
                'matakuliah_id'=> 1,
                'nilai_angka' => 64,
                'nilai_huruf'=>'C+',
            ],
            [   'mahasiswa_id' => 5,
                'matakuliah_id'=> 2,
                'nilai_angka' => 79,
                'nilai_huruf'=>'B+',
            ],
            [   'mahasiswa_id' => 5,
                'matakuliah_id'=> 3,
                'nilai_angka' => 85,
                'nilai_huruf'=>'A',
            ],
            [   'mahasiswa_id' => 6,
                'matakuliah_id'=> 4,
                'nilai_angka' => 78,
                'nilai_huruf'=>'B+',
            ],
            [   'mahasiswa_id' => 7,
                'matakuliah_id'=> 1,
                'nilai_angka' => 73,
                'nilai_huruf'=>'B',
            ],
            [   'mahasiswa_id' => 7,
                'matakuliah_id'=> 2,
                'nilai_angka' => 60,
                'nilai_huruf'=>'C',
            ],
            [   'mahasiswa_id' => 7,
                'matakuliah_id'=> 3,
                'nilai_angka' => 90,
                'nilai_huruf'=>'A',
            ],
            [   'mahasiswa_id' => 7,
                'matakuliah_id'=> 4,
                'nilai_angka' => 85,
                'nilai_huruf'=>'A',
            ],
            [   'mahasiswa_id' => 8,
                'matakuliah_id'=> 1,
                'nilai_angka' => 78,
                'nilai_huruf'=>'B+',
            ],
            [   'mahasiswa_id' => 8,
                'matakuliah_id'=> 2,
                'nilai_angka' => 73,
                'nilai_huruf'=>'B',
            ],
        
            [   'mahasiswa_id' => 8,
                'matakuliah_id'=> 3,
                'nilai_angka' => 69,
                'nilai_huruf'=>'B',
            ],
        
            [   'mahasiswa_id' => 8,
                'matakuliah_id'=> 4,
                'nilai_angka' => 92,
                'nilai_huruf'=>'A',
            ],
            [   'mahasiswa_id' => 9,
                'matakuliah_id'=> 1,
                'nilai_angka' => 80,
                'nilai_huruf'=>'B+',
            ],
            [   'mahasiswa_id' => 9,
                'matakuliah_id'=> 2,
                'nilai_angka' => 82,
                'nilai_huruf'=>'A',
            ],
            [   'mahasiswa_id' => 9,
                'matakuliah_id'=> 3,
                'nilai_angka' => 72,
                'nilai_huruf'=>'B',
            ],
            [   'mahasiswa_id' => 9,
                'matakuliah_id'=> 4,
                'nilai_angka' => 64,
                'nilai_huruf'=>'C+',
            ],
            [   'mahasiswa_id' => 10,
                'matakuliah_id'=> 1,
                'nilai_angka' => 85,
                'nilai_huruf'=>'A',
            ],
            [   'mahasiswa_id' => 10,
                'matakuliah_id'=> 2,
                'nilai_angka' => 89,
                'nilai_huruf'=>'A',
            ],
            [   'mahasiswa_id' => 10,
                'matakuliah_id'=> 3,
                'nilai_angka' => 79,
                'nilai_huruf'=>'B+',
            ],
            [   'mahasiswa_id' => 10,
                'matakuliah_id'=> 4,
                'nilai_angka' => 98,
                'nilai_huruf'=>'A',
            ],
        ];
        DB::table('mahasiswa_matakuliah')->insert($khs);
    }
}
